### ISSUE TITLE
server.properties seems somewhat ignored

### ISSUE THREAD

**Issue by zorel** [ich777/docker-minecraft-bedrock#2]
Hello.

I try to configure a creative game with everybody as operators and it fails, it "fallbacks" to survival with no operators.

I try to configure a survival game with everybody as operators, and same, it fails with no operators.

The logs show correctly the "Game mode: 1 Creative", but when i connect i'm in survival.

The name of the game however, is correctly set up. See attached filed.

![2020-02-16 16_51_15-Greenshot capture form](https://user-images.githubusercontent.com/630762/74607878-d08ab580-50dc-11ea-9c1a-6650da096cfc.png)
[ich777-minecraftbedrockserver1.log](https://github.com/ich777/docker-minecraft-bedrock/files/4210114/ich777-minecraftbedrockserver1.log)

Thanks.

**Comment by ich777** [comment]
Have you configured your premissions.json right and also changed the setting 'allow-cheats' to 'true' (since it's not possible to issue OP commands with it disabled)?

In your main directory should be a file called 'bedrock_server_how_to' there is all the information you need (since i'm not very familar with bedrock edition i can't really help).

I did a quick test on it and everything seems to work fine (I've also included my log file at the bottom and it loads everything correctly and also if I join the game it works fine in creative mode.

I found several issues on google but i think this has something to do with the game itself.

[Log.txt](https://github.com/ich777/docker-minecraft-bedrock/files/4210293/Log.txt)

**Comment by ich777** [comment]
@zorel Have you found the solution for your problem so that i can close the issue?

**Comment by zorel** [comment]
> Have you configured your premissions.json right and also changed the setting 'allow-cheats' to 'true' (since it's not possible to issue OP commands with it disabled)?
> 
> In your main directory should be a file called 'bedrock_server_how_to' there is all the information you need (since i'm not very familar with bedrock edition i can't really help).
> 

Yes, I gave myself operator rights. Still not operator on the game.

> I did a quick test on it and everything seems to work fine (I've also included my log file at the bottom and it loads everything correctly and also if I join the game it works fine in creative mode.

Well, the log shows the Survival mode, not creative.

Anyway, it works with some others images.

> 
> I found several issues on google but i think this has something to do with the game itself.
> 
> [Log.txt](https://github.com/ich777/docker-minecraft-bedrock/files/4210293/Log.txt)
